#!/bin/bash

# 0 = ORDI seulement
# 1 = HDMI seulement
# 2 = both

if [ $# -ne 1 ]; then exit 1; fi

ARG=$1

if [ $ARG -eq 0 ]; then
  pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo  
  xrandr --output HDMI1 --off --output LVDS1 --auto
elif [ $ARG -eq 1 ]; then
  pacmd set-card-profile 0 output:hdmi-stereo
  xrandr --output HDMI1 --auto --output LVDS1 --off
else
  pacmd set-card-profile 0 output:analog-stereo+input:analog-stereo
  xrandr --output LVDS1 --auto --primary --output HDMI1 --auto --right-of LVDS1
fi
